server:
  error:
    include-message: always
    include-binding-errors: always
  port: 8080

spring:
  config:
    import: classpath:dbConfig.properties
  datasource:
    password: ${datasource.password}
    url: ${datasource.url}
    username: ${datasource.username}
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true

  mail:
    host: localhost
    port: 1025
    username: hello
    password: hello

    properties:
      mail:
        smtp:
          ssl:
            trust: "*"
          auth: true
          starttls:
            enable: true
          connectionTimeout: 5000
          timeout: 3000
          writeTimeout: 5000